(DATA  a)
(FUNCTION  main  []
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Load [(r 2)]  [(s a)])
    (OPER 5 Mov [(r 3)]  [(i 0)])
    (OPER 6 Store [(s a)]  [(r 3)])
    (OPER 7 Mov [(r 5)]  [(i 1)])
    (OPER 8 Add_I [(r 6)]  [(r 2)(r 5)])
    (OPER 9 Mov [(r 1)]  [(r 6)])
    (OPER 10 Div_I [(r 7)]  [(r 2)(r 2)])
    (OPER 11 Mov [(r 8)]  [(i 3)])
    (OPER 12 Mul_I [(r 9)]  [(r 7)(r 8)])
    (OPER 13 Sub_I [(r 10)]  [(r 1)(r 9)])
    (OPER 14 Mov [(r 11)]  [(i 4)])
    (OPER 15 Add_I [(r 12)]  [(r 10)(r 11)])
    (OPER 16 Store [(s a)]  [(r 12)])
  )
  (BB 4
    (OPER 17 Func_Exit []  [])
    (OPER 18 Return []  [(m RetReg)])
  )
)
